causalens/cai-causal-graph

- .github/CODEOWNERS
- .github/workflows/pr-checks.yml
Allow Causal AI and MLE teams to own certain directories: source, test, and docs.
For info regarding format of CODEOWNERS see this [link](https://docs.github.com/en/repositories/managing-your-repositorys-settings-and-features/customizing-your-repository/about-code-owners).
> Repo: Extend CODEOWNERS to other teams in certain directories

- .github/workflows/main-checks.yml
- .github/workflows/pr-checks.yml
- Makefile
- README.md
- changelog.md
- docs/causal_graph.md
- pyproject.toml
Add `bandit` security linting to the package (just looking at the source code and not the tests).
For more info on `bandit` see [here](https://github.com/PyCQA/bandit).
Tested locally and added to PR and main checks.
> Repo: Add security linting with bandit

- cai_causal_graph/__init__.py
- cai_causal_graph/causal_graph.py
- poetry.lock
- pyproject.toml
The `<>` was seen as an unclosed tag. See failed job [here](https://github.com/causalens/causal-ai-website/actions/runs/5974356971/job/16208338329) when trying to deploy update to the docs site.
I did a dev tag and tried to deploy docs again. This now [works](https://github.com/causalens/causal-ai-website/actions/runs/6027221122).
> Docs: Fix docstring so docs can be built

- cai_causal_graph/causal_graph.py
- cai_causal_graph/graph_components.py
- cai_causal_graph/time_series_causal_graph.py
- changelog.md
- tests/test_causal_graph.py
- tests/test_time_series_graph.py
Fix `repr` bug in `TimeSeriesCausalGraph`, add more unit tests, and added an `__eq__` method for `TimeSeriesNode`.
Lots of new unit tests.
> Improvement: Fix repr bug in TimeSeriesCausalGraph and other small fixes

- README.md
- cai_causal_graph/__init__.py
- cai_causal_graph/graph_components.py
- cai_causal_graph/time_series_causal_graph.py
- changelog.md
- docs/quickstart.md
- poetry.lock
- pyproject.toml
- tests/test_time_series_graph.py
This PR addresses the following UAT feedback:
- Fixed code to deal with non-DAGs graphs (e.g. CPDAG, PAG, etc)
- Added tests to check edge types are preserved
- Improved logging when extending a graph
-  Added `cai_causal_graph.time_series_causal_graph.TimeSeriesCausalGraph.add_time_edge` method to add a time edge
between two nodes. This method allows to specify the time lag for source and destination variables. This avoids
having to create the corresponding node name manually or using the utility function `cai_causal_graph.utils.get_name_with_lag`.
- Changed the `cai_causal_graph.time_series_causal_graph.TimeSeriesCausalGraph.extend_gragh` method to work with
a non-negative `backward_steps` and `forward_steps` instead of strictly positive.
- Added …
> Improvement: UAT feedback

- changelog.md
- docs/quickstart.md
Good catch from Igor during UAT.
> Docs: Fix typo in quickstart

- cai_causal_graph/graph_components.py
- changelog.md
This is just to bring the API in line a bit more. We have properties and getters for a lot of attributes in the `Node`, `TimeSeriesNode,` and `Edge` classes. But `edge_type` only had a getter with no property so wanted to add it for consistency. 
> Improvement: Add edge_type property to Edge class

- cai_causal_graph/identify_utils.py
- changelog.md
- docs/causal_graph.md
- docs/causal_graph_utils.md
- docs/sidebar.json
- tests/test_identify_utils.py
This PR adds the `identify_confounders` utility function, which allows you to identify a list of confounders between two nodes within a causal graph.
> Feature: Identify Confounders Utility Function

- cai_causal_graph/causal_graph.py
- cai_causal_graph/identify_utils.py
- docs/causal_graph_utils.md
- docs/sidebar.json
- tests/test_identify_utils.py
Fix some error cases, improve memory usage, and extend to `NodeLike`. No changelog necessary as the previous feature was not released. Therefore prior message is sufficient.
New unit tests.
> Improvement: Improve identify confounders function

- cai_causal_graph/identify_utils.py
- changelog.md
- docs/causal_graph_utils.md
- tests/test_identify_utils.py
This PR adds `identify_mediators` and `identify_instruments`, and also abstracts away the `_verify_identify_inputs` protected method.
> Feature: Identify Mediator and Identify Instruments

- cai_causal_graph/__init__.py
- cai_causal_graph/causal_graph.py
- cai_causal_graph/time_series_causal_graph.py
- changelog.md
- pyproject.toml
- tests/test_causal_graph.py
- tests/test_skeleton.py
- tests/test_time_series_graph.py
- Made `copy` method in `CausalGraph` more general to preserve the class type.
- Removed `copy` from `TimeSeriesCausalGraph`.
Unit
> Improvement: Made method `copy` more general

- .github/workflows/dependencies-checks.yml
- .github/workflows/main-checks.yml
- .github/workflows/post-release.yml
- .github/workflows/pr-checks.yml
- changelog.md
- pyproject.toml
Wanted to expand support to `python` 3.12 so we can start supporting in some of our internal packages. Still have 3.11 has the default version for the workflows.
Also removed the caching in dep checks as was done on other internal packages. This was due to issues with GitHub using cache for a specific python version on another version.
Current unit tests. Added 3.12 to PR check right now to confirm it works.
> Improvement: Add support for python 3.12

- cai_causal_graph/time_series_causal_graph.py
- changelog.md
- tests/test_time_series_graph.py
Added the `cai_causal_graph.time_series_graph.TimeSeriesGraph.get_nodes_at_lag` and
`cai_causal_graph.time_series_graph.TimeSeriesGraph.get_contemporaneous_nodes` methods to the
`cai_causal_graph.time_series_graph.TimeSeriesGraph` class.
- Improved from_* for `TimeSeriesCausalGraph`
Unit tests
> Feature: Added utils to get contemporaneous nodes

- cai_causal_graph/causal_graph.py
- cai_causal_graph/time_series_causal_graph.py
- changelog.md
- tests/test_time_series_graph.py
- Improved the topological order to take into account time.
- Fixed bug in `cai_causal_graph.causal_graph.CausalGraph` and `cai_causal_graph.time_series_causal_graph.TimeSeriesCausalGraph` that
prevented `cai_causal_graph.time_series_causal_graph.TimeSeriesCausalGraph.get_minimal_graph`, `cai_causal_graph.time_series_causal_graph.TimeSeriesCausalGraph.get_summary_graph` and `cai_causal_graph.time_series_causal_graph.TimeSeriesCausalGraph.extend_graph` from working properly as it did not maintain the correct extra information such as node variable types.
Unit tests
> Bugfix: Node variable info

- cai_causal_graph/time_series_causal_graph.py
- changelog.md
- tests/test_time_series_graph.py
Modified `cai_causal_graph.time_series_causal_graph.TimeSeriesCausalGraph.add_edge` in 
`cai_causal_graph.time_series_causal_graph.TimeSeriesCausalGraph` to always order source and destination nodes by
`time_lag` even when the edge is not directed. For example, `add_edge('c', 'a (lag=1)', edge_type='--')` will add an 
undirected edge `a (lag=1) -- c` instead of `c -- a (lag=1)`. This is done just for convenience and to avoid confusion.
unit tests
- [] I have implemented all requirements? (see JIRA, project documentation)
> Improvements: Swapped source and destination in time series graph for non-directed edges

- .github/workflows/dependencies-checks.yml
Linting failed randomly on `main` so would want dep checks to run this to highlight failure sooner.
No changelog needed.
> Repo: Improve dep checks with additional checks in case some dev dependencies update

- cai_causal_graph/time_series_causal_graph.py
- changelog.md
The example was broken and did not render properly. This PR cleans it up.
> Docs: Fixed Docstring Example of TimeSeriesCausalGraph.from_adjacency_matrices

- README.md
- cai_causal_graph/__init__.py
- cai_causal_graph/type_definitions.py
- changelog.md
Redefined the `EdgeConstraint` enumeration to better match edge constraints used by other packages. This enumeration is not used in `cai-causal-graph` but is used by `dara`. Therefore, a backwards compat warning is added.
Existing unit tests.
> Improvement: Update EdgeConstraint to simplify enumeration members

- cai_causal_graph/time_series_causal_graph.py
- changelog.md
- tests/test_time_series_graph.py
> Bugfix: Forward graph extension

- changelog.md
- docs/causal_graph.md
- docs/quickstart.md
What it says on the tin. Essentially want to show how to control `variable_type` as this is needed in higher order product docs.
N/A
> Docs: Show how to set variable_type in quickstart

- cai_causal_graph/time_series_causal_graph.py
- changelog.md
- tests/test_time_series_graph.py
This PR:
- Fixed a bug in `cai_causal_graph.time_series_causal_graph.TimeSeriesCausalGraph.from_causal_graph` for `cai_causal_graph.time_series_causal_graph.TimeSeriesCausalGraph` where the method was not adding the node correctly.
- Added `max_time_lag` and `min_time_lag` properties to `cai_causal_graph.time_series_causal_graph.TimeSeriesCausalGraph` to return the maximum and minimum lag of the graph, respectively. The property `maxlag` was removed to avoid confusion.
> Bugfix: Added node properly in from_causal_graph

- cai_causal_graph/time_series_causal_graph.py
- changelog.md
- tests/test_time_series_graph.py
- Fixed a bug in the `cai_causal_graph.time_series_causal_graph.TimeSeriesCausalGraph.get_topological_order` method in
`cai_causal_graph.time_series_causal_graph.TimeSeriesCausalGraph` where the method was not working properly.
- [UAT feedback](https://www.notion.so/Coerce-time-tiers-586b2f68b9924ebf841e780ce4531679?d=eebff90e269b429ab085503fef58130f)
- [Slack thread](https://causalens.slack.com/archives/CHSPE3A94/p1702372017390759)
> Bugfix: Time series topological ordering

- cai_causal_graph/time_series_causal_graph.py
- changelog.md
- tests/test_time_series_graph.py
- Fixed a bug in `cai_causal_graph.time_series_causal_graph.TimeSeriesCausalGraph.get_minimal_graph` where the method was not adding the floating nodes correctly and it would return an empty graph. This also impacted the graph extension.
> Bugfix: min cg floating nodes

- cai_causal_graph/identify_utils.py
- changelog.md
- tests/test_identify_utils.py
- Improved efficiency of `cai_causal_graph.identify_utils.identify_confounders` by performing all operations
directly using `networkx`, removing the need to copy graphs and improving recursive logic, such that
only the minimal confounders of the specified nodes are calculated (rather than recursively calculating minimal
confounders of each parent). This results in significant speedups (in the order of hundreds of times in some cases).
> Improvement: improve efficiency of cai_causal_graph.identify_utils.identify_confounders

- cai_causal_graph/causal_graph.py
- changelog.md
- tests/test_causal_graph.py
- tests/test_time_series_graph.py
- Added `cai_causal_graph.causal_graph.CausalGraph.add_edges_from_paths` convenience method to add edges from paths.
> Improvement: CausalGraph.add_edges_from_paths

- cai_causal_graph/causal_graph.py
- cai_causal_graph/utils.py
- changelog.md
- Fixed bug where use of `itertools.pairwise` would result in errors for Python \< 3.10.
> Bug: itertools.pairwise in Python < 3.10

- cai_causal_graph/__init__.py
- cai_causal_graph/time_series_causal_graph.py
- changelog.md
- poetry.lock
- pyproject.toml
- `cai_causal_graph.time_series_causal_graph.TimeSeriesCausalGraph.get_minimal_graph` will now always return a graph of the
same class type as the current graph instance.
- The returned graph type from `cai_causal_graph.time_series_causal_graph.TimeSeriesCausalGraph.get_summary_graph` can
now be specified in subclasses of `cai_causal_graph.time_series_causal_graph.TimeSeriesCausalGraph` using the
`_SummaryGraphCls` attribute.
These changes were made so that subclasses work correctly without having to reimplement methods where only a class instantiation would change. See https://github.com/causalens/causalnet/pull/271 for tests that verify that these changes work.
> Bug: Fix issues when subclassing CausalGraph

- cai_causal_graph/causal_graph.py
- changelog.md
- The `cai_causal_graph.causal_graph.CausalGraph.from_adjacency_matrix` is now a class method (rather than being a static method)
which has been generalized to return an instance of the class on which it has been called (e.g. enabling returning instances of
classes inheriting from `cai_causal_graph.causal_graph.CausalGraph`.
This is to simplify extending `CausalGraph` class and to bring `from_adjancency_matrix` in line with other class construction methods such as `from_dict`.
This change is completely backwards compatible since the API of the method is unchanged.
Existing tests.
> Improvement: generalize CausalGraph.from_adjacency_matrix

- cai_causal_graph/__init__.py
- cai_causal_graph/causal_graph.py
- cai_causal_graph/time_series_causal_graph.py
- changelog.md
- poetry.lock
- pyproject.toml
Added the `validate` flag to `cai_causal_graph.causal_graph.CausalGraph.add_edge`,
`cai_causal_graph.causal_graph.CausalGraph.add_edges_from`,
`cai_causal_graph.causal_graph.CausalGraph.add_edges_from_paths`,
`cai_causal_graph.causal_graph.CausalGraph.add_edge_by_pair`,
`cai_causal_graph.causal_graph.CausalGraph.from_dict`,
`cai_causal_graph.time_series_causal_graph.TimeSeriesCausalGraph.add_edge`, and
`cai_causal_graph.time_series_causal_graph.TimeSeriesCausalGraph.add_time_edge` which, if set to `False`, will disable validation checks. Currently, this disables cyclicity checks when adding edges. Default is `True`, making the change backwards compatible. There is no guarantees about the behavior of the resulting graph if this is disabled specifically to introduce cycles. This should only …
> Improvement: Skip validation checks

- cai_causal_graph/causal_graph.py
- changelog.md
- tests/test_causal_graph.py
- tests/test_time_series_graph.py
This PR adds the `CausalGraph.replace_edge` method that allows you to replace an existing edge with a new one.
Among other things, this allows you to swap the direction of an edge.
> Feature: Method to replace an edge

- cai_causal_graph/graph_components.py
- cai_causal_graph/time_series_causal_graph.py
- changelog.md
- tests/test_components.py
- tests/test_time_series_graph.py
- Added the `cai_causal_graph.time_series_causal_graph.TimeSeriesCausalGraph.get_nodes_for_variable_name` method to the  `cai_causal_graph.time_series_causal_graph.TimeSeriesCausalGraph` class.
- Added the `cai_causal_graph.graph_components.Node.is_source_node` and `cai_causal_graph.graph_components.Node.is_sink_node`
methods to the `cai_causal_graph.graph_components.Node`, indicating whether the node is a source node or sink node
respectively.
Added unit tests
> Feature: Extra utility methods

- cai_causal_graph/__init__.py
- cai_causal_graph/causal_graph.py
- cai_causal_graph/graph_components.py
- cai_causal_graph/time_series_causal_graph.py
- changelog.md
- poetry.lock
- pyproject.toml
- tests/test_causal_graph.py
- tests/test_skeleton.py
- tests/test_time_series_graph.py
Updated to/from methods to ensure the type matches the calling class.  There is also a small bug fix where the node variable type was not passed to the skeleton node.
Part of a wider effort to improve the generalisation of the base `CausalGraph` class.
Extended unit tests. Also added some tests for JSON serialisability of `Skeleton`.
> Improvements: More general to and from methods

- changelog.md
- pyproject.toml
What it says on the tin. We need to make `mypy` a dep and not dev dep as we import from it in source code. However, range was too narrow.
Existing unit tests.
> Repo: Relax mypy dependency

- cai_causal_graph/time_series_causal_graph.py
- changelog.md
- pyproject.toml
- tests/test_time_series_graph.py
Fixed a bug in `cai_causal_graph.time_series_causal_graph.TimeSeriesCausalGraph.from_adjacency_matrices` for
`cai_causal_graph.time_series_causal_graph.TimeSeriesCausalGraph` where the method was not handling properly
undirected edges in the adjacency matrices.
> Bugfix: from_adjacency_matrices in TimeSeriesCausalGraph

- cai_causal_graph/__init__.py
- cai_causal_graph/time_series_causal_graph.py
- changelog.md
- poetry.lock
- pyproject.toml
- tests/test_conversions.py
- tests/test_time_series_graph.py
The bugfix in https://github.com/causalens/cai-causal-graph/pull/60 still had an issue.
New unit tests
> Bugfix: Complete the bugfix in from adj matrices for time series graph

- cai_causal_graph/time_series_causal_graph.py
- changelog.md
- tests/test_time_series_graph.py
Added `cai_causal_graph.time_series_causal_graph.TimeSeriesCausalGraph.cache_nodes` and
`cai_causal_graph.time_series_causal_graph.TimeSeriesCausalGraph.cache_nodes` to avoid having to loop
through the nodes of the graph multiple times in `cai_causal_graph.time_series_causal_graph.TimeSeriesCausalGraph.get_nodes_at_lag` and `cai_causal_graph.time_series_causal_graph.TimeSeriesCausalGraph.get_nodes_for_variable`
> Store a map of nodes in TimeSeriesCausalGraph

- cai_causal_graph/identify_utils.py
- changelog.md
- docs/causal_graph_utils.md
- tests/test_identify_utils.py
Added the `cai_causal_graph.causal_graph.identify_utils.identity_colliders` utility function, which allows to identify a list of colliders in a `cai_causal_graph.causal_graph.CausalGraph`.
> Feature: Added collider utils

- .github/workflows/dependencies-checks.yml
- .github/workflows/main-checks.yml
- .github/workflows/pr-checks.yml
- .github/workflows/release.yml
- changelog.md
What it says on the tin.
To align with our internal packages.
N/A
> Repo: Update poetry and repository-dispatch action

- Makefile
- cai_causal_graph/__init__.py
- changelog.md
- pyproject.toml
The doc building and deploying was failing. Originally thought this was due to `docs-builder` but it is due to upgrade to `poetry`. Need to change syntax for specifying the causalens source in the Makefile.
Pushed a dev tag to see if docs build and publish correctly. See [here](https://github.com/causalens/cai-causal-graph/actions/runs/8631788668/job/23660937847).
> Repo: Update docs-builder to ~0.2.1

- cai_causal_graph/time_series_causal_graph.py
- changelog.md
- tests/test_time_series_graph.py
- Fixed a bug where metadata on floating nodes would not be correctly carried over to the minimal graph when calling
`cai_causal_graph.time_series_causal_graph.TimeSeriesCausalGraph.get_minimal_graph`. This also fixes an issue where
`cai_causal_graph.time_series_causal_graph.TimeSeriesCausalGraph.is_minimal_graph` could return `False` on minimal
graphs that contain floating nodes.
Unit tests
> Bug: is_minimal_graph with floating nodes

- cai_causal_graph/causal_graph.py
- cai_causal_graph/time_series_causal_graph.py
- changelog.md
- docs/time_series_causal_graph.md
Cleaned up the syntax in various places to support the new docs building process
> Docs: Syntax Clean-Up

- .github/workflows/dependencies-checks.yml
- .github/workflows/post-release.yml
- README.md
- changelog.md
- pyproject.toml
Drop `python` `3.8` support as it is approaching end of life.
> Improvement: Drop python 3.8 support 

- cai_causal_graph/time_series_causal_graph.py
- changelog.md
- docs/time_series_causal_graph.md
- tests/test_time_series_graph.py
- The default value of the `include_all_parents` argument to `cai_causal_graph.time_series_causal_graph.TimeSeriesCausalGraph.extend_graph`
has been changed to `True` (from `False`).
> Improvement: change `include_all_parents` default value of `TimeSeriesCausalGraph.extend_graph`

- cai_causal_graph/causal_graph.py
- changelog.md
- tests/test_causal_graph.py
Add is dag to graph repr. This is to help with the package analytics.
Extended unit tests.
> Improvement: Add is dag to repr for CausalGraph

- cai_causal_graph/causal_graph.py
- cai_causal_graph/time_series_causal_graph.py
- changelog.md
- tests/test_causal_graph.py
- tests/test_time_series_graph.py
- Improved caching of results for `cai_causal_graph.time_series_causal_graph.TimeSeriesCausalGraph` class, including:
- Adding caching to the following methods: `cai_causal_graph.time_series_causal_graph.TimeSeriesCausalGraph.get_minimal_graph`, `cai_causal_graph.time_series_causal_graph.TimeSeriesCausalGraph.is_minimal_graph`,
`cai_causal_graph.time_series_causal_graph.TimeSeriesCausalGraph.is_stationary_graph`.
- Fixed a bug in `cai_causal_graph.time_series_causal_graph.TimeSeriesCausalGraph.get_stationary_graph` where the same cached graph would be returned multiple times. Instead now,
a deepcopied version of this graph is returned.
- Fixed a bug where cached attributes would not be reset when adding edges to `cai_causal_graph.time_series_causal_graph.TimeSeriesCausalGraph`, which can …
> Improvement: improvements to caching of attributes

- cai_causal_graph/time_series_causal_graph.py
- changelog.md
- tests/test_time_series_graph.py
- Removed caching from `cai_causal_graph.time_series_causal_graph.TimeSeriesCausalGraph.get_minimal_graph`, `cai_causal_graph.time_series_causal_graph.TimeSeriesCausalGraph.get_stationary_graph` and
`cai_causal_graph.time_series_causal_graph.TimeSeriesCausalGraph.get_summary_graph` because the caching would not account for changes
in node/edge metadata.
> Bug: remove caching from methods which return a graph with metadata.

- .github/workflows/dependencies-checks.yml
- .github/workflows/main-checks.yml
- .github/workflows/pr-checks.yml
- .github/workflows/release.yml
- changelog.md
To align with our internal packages.
Current workflows
> Maintenance: Update poetry to 1.8.3

- cai_causal_graph/utils.py
- changelog.md
- tests/test_time_series_utils.py
- `cai_causal_graph.utils.get_variable_name_and_lag` now allows new lines in the names of variables.
> Improvement: new lines in variable names

- cai_causal_graph/time_series_causal_graph.py
- changelog.md
- tests/test_time_series_graph.py
What it says on the tin.
Regression test added.
> Bugfix: Ensure floating nodes are maintained in summary graph

- cai_causal_graph/causal_graph.py
- changelog.md
Identified inefficiencies around large graphs trying to filter them down, looping over all nodes and edges to delete in previous method was too slow.
This PR speeds things up by factors of 10s or 100s even depending on graph size.
It improves things from 75s  -> 0.5s, 126x speedup
> Feature: Speeding up get_ancestral_graph, get_descendant_graph

- changelog.md
> Maintenance: format changelog
